### ISSUE TITLE
Does deDoc2 contain a parameter that controls the size of the TLDs it found?

### ISSUE THREAD

**Issue by dangdachang** [zengguangjie/deDoc2#1]
Hello, I would like to know if there is a way to control the size of the identified TLDs in deDoc2. Can the parameter '-windowsize' control the size of TLD?  Or the TLDs are only divided into two types by deDoc2.w and deDoc2.s.

**Comment by zengguangjie** [comment]
Yes, the parameter '-windowsize' is related to the output TLD size. However, the algorithm does not guarantee to produce TLD with acceptable quality if the '-windowsize' is too small. Feel free to give it a try.
